package sici.modelo;
// Generated 18/10/2017 21:00:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer idMovimiento;
     private Articulo articulo;
     private Responsable responsable;
     private Usuario usuario;
     private Date fechaMovimiento;
     private Integer tipoMovimiento;
     private Integer cantidadArticulo;
     private Integer numTransaccion;

    public Almacen() {
    }

	
    public Almacen(Articulo articulo, Responsable responsable, Usuario usuario) {
        this.articulo = articulo;
        this.responsable = responsable;
        this.usuario = usuario;
    }
    public Almacen(Articulo articulo, Responsable responsable, Usuario usuario, Date fechaMovimiento, Integer tipoMovimiento, Integer cantidadArticulo, Integer numTransaccion) {
       this.articulo = articulo;
       this.responsable = responsable;
       this.usuario = usuario;
       this.fechaMovimiento = fechaMovimiento;
       this.tipoMovimiento = tipoMovimiento;
       this.cantidadArticulo = cantidadArticulo;
       this.numTransaccion = numTransaccion;
    }
   
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Responsable getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(Responsable responsable) {
        this.responsable = responsable;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaMovimiento() {
        return this.fechaMovimiento;
    }
    
    public void setFechaMovimiento(Date fechaMovimiento) {
        this.fechaMovimiento = fechaMovimiento;
    }
    public Integer getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(Integer tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }
    public Integer getCantidadArticulo() {
        return this.cantidadArticulo;
    }
    
    public void setCantidadArticulo(Integer cantidadArticulo) {
        this.cantidadArticulo = cantidadArticulo;
    }
    public Integer getNumTransaccion() {
        return this.numTransaccion;
    }
    
    public void setNumTransaccion(Integer numTransaccion) {
        this.numTransaccion = numTransaccion;
    }




}


