package sici.modelo;
// Generated 18/10/2017 21:00:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private int idArticulo;
     private Marca marca;
     private Unidad unidad;
     private Double precio;
     private String descripcion;
     private String nombre;
     private Integer existencia;
     private Integer estockMinimo;
     private String numSerie;
     private Integer estado;
     private int idEmpresa;
     private Set almacens = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int idArticulo, Marca marca, Unidad unidad, int idEmpresa) {
        this.idArticulo = idArticulo;
        this.marca = marca;
        this.unidad = unidad;
        this.idEmpresa = idEmpresa;
    }
    public Articulo(int idArticulo, Marca marca, Unidad unidad, Double precio, String descripcion, String nombre, Integer existencia, Integer estockMinimo, String numSerie, Integer estado, int idEmpresa, Set almacens, Set empresas) {
       this.idArticulo = idArticulo;
       this.marca = marca;
       this.unidad = unidad;
       this.precio = precio;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.existencia = existencia;
       this.estockMinimo = estockMinimo;
       this.numSerie = numSerie;
       this.estado = estado;
       this.idEmpresa = idEmpresa;
       this.almacens = almacens;
       this.empresas = empresas;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }
    public Integer getEstockMinimo() {
        return this.estockMinimo;
    }
    
    public void setEstockMinimo(Integer estockMinimo) {
        this.estockMinimo = estockMinimo;
    }
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Set getAlmacens() {
        return this.almacens;
    }
    
    public void setAlmacens(Set almacens) {
        this.almacens = almacens;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


