package sici.modelo;
// Generated 18/10/2017 21:00:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsable generated by hbm2java
 */
public class Responsable  implements java.io.Serializable {


     private int idResponsable;
     private Integer estado;
     private String nombre;
     private String direccion;
     private String dni;
     private String email;
     private String telefono;
     private Set almacens = new HashSet(0);

    public Responsable() {
    }

	
    public Responsable(int idResponsable) {
        this.idResponsable = idResponsable;
    }
    public Responsable(int idResponsable, Integer estado, String nombre, String direccion, String dni, String email, String telefono, Set almacens) {
       this.idResponsable = idResponsable;
       this.estado = estado;
       this.nombre = nombre;
       this.direccion = direccion;
       this.dni = dni;
       this.email = email;
       this.telefono = telefono;
       this.almacens = almacens;
    }
   
    public int getIdResponsable() {
        return this.idResponsable;
    }
    
    public void setIdResponsable(int idResponsable) {
        this.idResponsable = idResponsable;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getAlmacens() {
        return this.almacens;
    }
    
    public void setAlmacens(Set almacens) {
        this.almacens = almacens;
    }




}


